import { Router } from "express";
import authRoute from "../modules/auth/auth.route";
import heroRoute from "../modules/hero/hero.route";
import aboutRoute from "../modules/about/about.route";
import skillsRoute from "../modules/skills/skills.route";
import experienceRoute from "../modules/experience/experience.route";
import projectsRoute from "../modules/projects/projects.route";
import educationRoute from "../modules/education/education.route";
import certificatesRoute from "../modules/certificates/certificates.route";
import reviewsRoute from "../modules/reviews/reviews.route";
import blogsRoute from "../modules/blogs/blogs.route";
import contactRoute from "../modules/contact/contact.route";
import greetingRoute from "../modules/greeting/greeting.route";
import themeRoute from "../modules/theme/theme.route";
import publicRoute from "../modules/public/public.route";
import uploadRoute from "../modules/upload/upload.route";
import messagesRoute from "../modules/messages/messages.route";
import { ChatRoutes } from "../modules/chat/chat.route";
import knowledgeRoute from "../modules/knowledge/knowledge.route";

const router = Router();

router.use("/auth", authRoute);
router.use("/hero", heroRoute);
router.use("/about", aboutRoute);
router.use("/skills", skillsRoute);
router.use("/experience", experienceRoute);
router.use("/projects", projectsRoute);
router.use("/education", educationRoute);
router.use("/certificates", certificatesRoute);
router.use("/reviews", reviewsRoute);
router.use("/blogs", blogsRoute);
router.use("/contact", contactRoute);
router.use("/greeting", greetingRoute);
router.use("/chat", ChatRoutes);
router.use("/knowledge", knowledgeRoute);
router.use("/theme", themeRoute);
router.use("/upload", uploadRoute);
router.use("/messages", messagesRoute);

export { publicRoute };
export default router;
